version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=passport
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/passport/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  app:
    image: passport
    container_name: passport
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/passport
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8090:8090"
    depends_on:
      - db